project:
  type: website

website:
  title: "ISSS608-VAA-Huang Zihan"
  navbar:
    left: 
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html" 
          - text: "Hands-on Exercise 3-1"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_1.html" 
          - text: "Hands-on Exercise 3-2"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_2.html"
          - text: "Hands-on Exercise 4-1"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_1.html"
          - text: "Hands-on Exercise 4-2"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_2.html"
          - text: "Hands-on Exercise 4-3"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_3.html"
          - text: "Hands-on Exercise 4-4"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_4.html"
          - text: "Hands-on Exercise 5"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
          - text: "Hands-on Exercise 6"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
          - text: "Hands-on Exercise 8-1"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08-1.html" 
          - text: "Hands-on Exercise 8-2"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08-2.html" 
          - text: "Hands-on Exercise 8-3"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08-3.html" 
          - text: "Hands-on Exercise 9-1"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09-1.html" 
          - text: "Hands-on Exercise 9-2"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09-2.html" 
          - text: "Hands-on Exercise 9-3"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09-3.html" 
          - text: "Hands-on Exercise 9-4"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09-4.html" 
          - text: "Hands-on Exercise 9-5"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09-5.html" 
          - text: "Hands-on Exercise 10"
            href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html" 
      - text: "Take-home Exercise"
        menu: 
          - text: "Take-home Exercise 1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
          - text: "Take-home Exercise 2"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
          - text: "Take-home Exercise 3"
            href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
      - text: "VAST Challenge 2025"
        menu: 
          - text: "MC1"
            href: "VAST Challenge 2025/MC1/MC1.html"
          - text: "MC1 prototype"
            href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03_Prototype.html"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: Minty
    css: styles.css
    toc: true

editor: visual

